model:
  name: "Sequential-Character-Level-Language-Model"
  ckpt_name: "gru_best_model_smaller_vocab_finetune"
  pretrain_ckpt_path: "/root/makemore/personal-extension/character_level_lm/ckpt/gru_pretrain_best_model_smaller_vocab_seq_64.pth"
  architecture:
    type: "gru"

training:
  batch_size: 256
  sequence_length: 64
  epochs: 20
  learning_rate: 0.005

hardware:
  device: "cuda"