model:
  name: "Sequential-Character-Level-Language-Model"
  ckpt_name: "gru_best_model"
  architecture:
    type: "gru"
    num_layers: 2
    embedding_dim: 256
    hidden_dim: 256
    dropout: 0.0
    batch_first: True

training:
  batch_size: 256
  sequence_length: 64
  epochs: 12
  learning_rate: 0.001

hardware:
  device: "cuda"