model:
  name: "RNN-Character-Level-Language-Model"
  architecture:
    type: "rnn"
    num_layers: 2
    embedding_dim: 256
    hidden_dim: 256
    dropout: 0.2
    batch_first: True

training:
  batch_size: 256
  sequence_length: 64
  epochs: 10
  learning_rate: 0.001

hardware:
  device: "cuda"