model:
  name: "Sequential-Character-Level-Language-Model-Pretrain"
  ckpt_name: "gru_pretrain_best_model_smaller_vocab_seq_64"
  architecture:
    type: "gru"
    num_layers: 2
    embedding_dim: 256
    hidden_dim: 256
    dropout: 0.0
    batch_first: True

training:
  file_path: "/root/makemore/personal-extension/character_level_lm/pretrain_data_seq_len_64.npz"
  batch_size: 1024
  sequence_length: 64
  epochs: 2
  learning_rate: 0.01

hardware:
  device: "cuda"